# Temporary as I need to override the Netlify build settings for the site directory rename
[build]
  base= "site/"

[[redirects]]
  from = "/contribute"
  to = "/get-involved"
  status = 301

[[redirects]]
  from = "/components/popup.research.explainer"
  to = "/components/popover.research.explainer"
  status = 301

[[redirects]]
  from = "/components/selectmenu"
  to = "/components/customizableselect"
  status = 301

[[redirects]]
  from = "/components/selectlist"
  to = "/components/customizableselect"
  status = 301

[[redirects]]
  from = "/components/select"
  to = "/components/customizableselect"
  status = 301
